name: Continuous Integration

on:
  push:
    branches:
      - "*"
      - "*/*"
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: windows-latest

    strategy:
      matrix:
        dotnet: [
          { framework: net48, version: 5.0.102 },
        ]

    name: ${{ matrix.dotnet.framework }} – run tests

    steps:
      - uses: actions/checkout@v2

      - name: Start Cosmos DB Emulator
        shell: powershell
        run: |
          Import-Module "$env:ProgramFiles\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"
          Start-CosmosDbEmulator

      - name: Run tests
        env:
          COSMOS_CONNECTION_STRING: "AccountEndpoint=https://localhost:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=="
        run: |
          dotnet test --configuration Release --framework ${{ matrix.dotnet.framework }} ./Dodo.AspNet.SessionProviders.CosmosDb.Tests/Dodo.AspNet.SessionProviders.CosmosDb.Tests.csproj /p:Framework=${{ matrix.dotnet.framework }}