name: Continuous Integration

on:
  push:
    branches:
      - "*"
      - "*/*"
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: windows-latest

    strategy:
      matrix:
        dotnet: [
          { framework: net48, version: 5.0.102 },
        ]

    name: ${{ matrix.dotnet.framework }} – run tests

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          dotnet test --configuration Release --framework ${{ matrix.dotnet.framework }} ./DodoBrands.AspNet.SessionProviders.Tests/DodoBrands.AspNet.SessionProviders.Tests.csproj /p:Framework=${{ matrix.dotnet.framework }}